import-path: /etc/.credentials

spring:
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db,imageHostingReadiness

  tracing:
    sampling:
      probability: 1.0