import-path: /dev/config

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.core.env: TRACE
    org.springframework.boot.context.config: DEBUG
    com.zaxxer: DEBUG