spring:
  application:
    name: sandbox-service
  cloud:
    kubernetes:
      secrets:
        enabled: true
        name: bricklink
        namespace: sandbox
        sources:
          - name: bricklink-client-api-keys
        fail-fast: true
        paths: /etc/.credentials/bricklink-client-api-keys
      config:
        fail-fast: true

logging:
  level:
    root: debug
