import-path: /dev/config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: false
  defaults:
    metrics:
      export:
        enabled: false

logging:
  level:
    root: INFO