spring:
  application:
    name: sandbox-service
  cloud:
    kubernetes:
      secrets:
        enabled: true
        name: bricklink-client-api-keys
        namespace: sandbox
        sources: /etc/.credentials/bricklink-client-api-keys

