spring:
  datasource:
    database-key-name: legolandserver1-lego-sandbox
  config:
    import: file:${import-path}/bricklink/bricklink-client-api-keys.json, file:${import-path}/bricklink/bricklink-web.json


management:
  endpoints:
    web:
      exposure:
        include: "*"

