apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-sandbox-service
spec:
  template:
    spec:
      containers:
        - name: lego-sandbox-service
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
