apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-sandbox-service-deployment
  namespace: services-sandbox
  labels:
    app: lego-sandbox-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lego-sandbox-service-deployment
  template:
    metadata:
      name: lego-sandbox-service-deployment
      labels:
        app: lego-sandbox-service-deployment
    spec:
      containers:
        - name: lego-sandbox-service-deployment
          image: quay.io/tvattima/lego-sandbox-service:snapshot
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ABC
              value: "123"
          volumeMounts:
            - name: bricklink-configuration
              mountPath: /etc/.credentials/bricklink
            - name: database-configuration
              mountPath: /etc/.credentials/database
      volumes:
        - name: bricklink-configuration
          secret:
            secretName: bricklink-configuration-secret
        - name: database-configuration
          secret:
            secretName: database-configuration-secret
      restartPolicy: Always
